# nixpacks.toml

[phases.setup]
nixpkgsArchive = '1bc6e6c0954a2089f067fac8cc43fa65a7d204cc'
#nixPkgs = ['...', 'cowsay']

#[phases.build]
#cmds = ['yarn run server:build']

#[start]
#cmd = 'yarn run server:start'
